### ISSUE TITLE
Add support for cleaning of VScode "workspaceStorage"

### ISSUE THREAD

**Issue by pbremondFR** [alexandregv/42toolbox#4]
Hi,

I was recently trying to free up some space, and found out that after some fair bit of using VScode, the `workspaceStorage` dir was taking a fair bit of useless space. Located in `/Users/username/Library/Application Support/Code/User/`, it can eat gigabytes worth of disk storage. AFAIK, there are no notable consequences, it's just cache for workspaces, most of which you won't be using any time soon.

A quick Google search reveals that `workspaceStorage` being so massive is a fairly common problem, and can be solved with a quick and easy `rm -rf`. Which is why I think it would fit nicely within this toolbox.

I'd make a pull request if I had any meaningful idea of what I'm doing, but since that's not the case, I'll leave it to whoever reads this.

Thanks for your time !

**Comment by alexandregv** [comment]
Hi, thanks for the suggestion. I added it in 0c486e46275edc5516f7b8ee4825f7147090f143.
