### ISSUE TITLE
cpp clean up

### ISSUE THREAD

**Issue by ghost** [alexandregv/42toolbox#5]
hi, in `/Users/your_intra/Library` , in cpp module, with vscode, there is a `vscode-cpptools` folder that take mor and more space to every new compilation . `rm -rf Caches/*` . remove this folder gived me back 3.5G

**Comment by alexandregv** [comment]
Hi, isn't it covered by https://github.com/alexandregv/42toolbox/blob/master/free_space.sh#L43 ?

**Comment by ghost** [comment]
I tryed again today, all is working. I don't know why it only worked manually yesterday
